name: HTML Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  html-validator:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v0.3.0
      with:
        root: .
